name: Build and Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v2

    - name: Set up Java 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build JAR using Maven
      run: mvn clean package

    - name: Copy JAR to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "target/aws-cost-optimizer-1.0-SNAPSHOT.jar"
        target: "/home/ec2-user/"

    - name: SSH into EC2 and Deploy App
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          echo "Creating deployment script on EC2"

          cat << 'EOF' > /home/ec2-user/start-app.sh
          #!/bin/bash
          echo "Killing old app if exists"
          pkill -f aws-cost-optimizer || true

          echo "Starting Spring Boot app"
          cd /home/ec2-user
          nohup java -jar aws-cost-optimizer-1.0-SNAPSHOT.jar > app.log 2>&1 &
          echo "App started successfully"
          EOF

          chmod +x /home/ec2-user/start-app.sh
          bash /home/ec2-user/start-app.sh