name: Build and Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v2

    - name: Set up Java 17
      uses: actions/setup-java@v2
      with:
	distribution: 'temurin'
        java-version: '17'

    - name: Build JAR using Maven
      run: mvn clean package

    - name: Copy JAR to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "target/aws-cost-optimizer-1.0-SNAPSHOT.jar"
        target: "/home/ec2-user/"

    - name: SSH into EC2 and Run App
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          pkill -f 'aws-cost-optimizer' || true
          nohup java -jar /home/ec2-user/aws-cost-optimizer-1.0-SNAPSHOT.jar > log.txt 2>&1 &
